// apps/tu-trader-next/components/MenuItem.tsx
import Link from "next/link";
import React from "react";

interface Props extends React.LiHTMLAttributes<{}> {
    title?: string;
    innerClass?: string;
    icon: string;
    to: string;
}
const MenuItem: React.FC<Props> = ({
    title,
    innerClass,
    icon,
    to,
    children,
}) => {
    return (
        <li className="tooltip tooltip-right" data-tip={title}>
            {to ? (
                <Link href={to} className="`${innerClass}`">
                    {icon && <i className={icon} />} {children}
                </Link>
            ) : (
                <span v-else className={`${innerClass}`}>
                    {icon && <i v-if="icon" className={icon} />} {children}
                </span>
            )}
        </li>
    );
};

export default MenuItem;

// apps/tu-trader-sv/src/components/MenuItem.svelte
<script lang="ts">
    import type { HTMLAttributes } from "svelte/elements";

    interface IProps extends HTMLAttributes<any> {
        to?: string;
        title?: string;
        innerClass?: string;
        icon?: string;
    }
    const {
        to,
        innerClass,
        children,
        title,
        icon,
        class: _class,
        ...props
    }: IProps = $props();
</script>

<li class={"tooltip tooltip-right " + _class} data-tip={title} {...props}>
    {#if to}
        <nuxt-link {to} class={`${innerClass}`}>
            {#if icon}
                <i class={icon}></i>
            {/if}
            {@render children?.()}
        </nuxt-link>
    {:else}
        <span class={`${innerClass}`}>
            {#if icon}
                <i class={icon}></i>
            {/if}
            {@render children?.()}
        </span>
    {/if}
</li>
