// apps/tu-trader-next/components/Sidebar.tsx
import MenuItem from "./MenuItem";

const Sidebar = () => {
    return (
        <aside>
            <ul className="menu gap-0 sm:gap-5  sidebar">
                <MenuItem
                    title="Home"
                    inner-className="justify-center"
                    icon="fi fi-rr-house-window"
                    to="/"
                />

                <MenuItem
                    title="Backtest"
                    inner-className="justify-center"
                    icon="fi fi-rr-blood-test-tube-alt"
                    to="/backtest"
                ></MenuItem>

                <MenuItem
                    title="Coin test"
                    inner-className="justify-center"
                    icon="fi fi-rr-coins"
                    to="/test/coins"
                ></MenuItem>
                <MenuItem
                    title="Arbitrage Coin test"
                    inner-className="justify-center"
                    icon="fi fi-rr-money-transfer-coin-arrow"
                    to="/test/arbit/coins"
                ></MenuItem>
            </ul>
        </aside>
    );
};

export default Sidebar;

// apps/tu-trader-sv/src/components/Sidebar.vue
<template>
    <aside >
        <ul class="menu gap-0 sm:gap-5  sidebar">
   
    
    <menu-item
            title="Home"
                inner-class="justify-center"
                icon="fi fi-rr-house-window"
                to="/"
            />
            
            <menu-item title="Backtest"
                
                inner-class="justify-center"
                icon="fi fi-rr-blood-test-tube-alt"
                to="/backtest"
            ></menu-item>
          
           
            <menu-item title="Coin test"
                
                inner-class="justify-center"
                icon="fi fi-rr-coins"
                to="/test/coins"
            ></menu-item>
            <menu-item title="Arbitrage Coin test"
                
                inner-class="justify-center"
                icon="fi fi-rr-money-transfer-coin-arrow"
                to="/test/arbit/coins"
            ></menu-item>
           
</ul>
    </aside>
</template>

<script setup lang="ts"></script>
