// apps/tu-trader-next/components/UAccordion.tsx
import React, { DetailsHTMLAttributes } from "react";

interface Props extends DetailsHTMLAttributes<{}> {
    children: React.ReactNode; label: React.ReactNode
}
const UAccordion: React.FC<Props> = ({ children, label }) => {
    return (
        <details className="collapse collapse-arrow border border-card bg-base-100 collapse-sm">
            <summary className="collapse-title text-l font-medium">
                {label}
            </summary>
            <div className="collapse-content">{children}</div>
        </details>
    );
};

export default UAccordion;

// apps/tu-trader-sv/src/components/UAccordion.svelte
    <details class={"collapse collapse-arrow border border-card bg-base-100 collapse-sm " + _class} {...props}>
        <summary class="collapse-title text-l font-medium">
            {@render label?.()}
        </summary>
        <div class="collapse-content">
            {@render content?.()}
        </div>
    </details>

<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLDetailsAttributes } from "svelte/elements";

    interface IProps extends HTMLDetailsAttributes{label?: Snippet; content?: Snippet}
    const {label, content, class: _class, ...props} : IProps = $props()
</script>
