// apps/tu-trader-next/components/UForm.tsx
import React from 'react';

interface Props extends React.HTMLAttributes<{}> {
    onSubmit?: (e: any)=>any; state?: any
}
const MyForm: React.FC<Props> = ({ onSubmit, children, ...props }) => {
    const handleSubmit = async (e) => {
        e.preventDefault();
        const btns: HTMLButtonElement[] = Array.from(e.target.querySelectorAll('button[type=submit]'));
        btns.forEach((btn) => {
            btn.disabled = true;
        });
        await onSubmit?.call(this, e);
        btns.forEach((btn) => (btn.disabled = false));
    };

    return (
        <form onSubmit={handleSubmit} {...props}>
            {children}
        </form>
    );
};

export default MyForm;

// apps/tu-trader-sv/src/components/UForm.svelte

    <form onsubmit={_onSubmit} {...props}>
        {@render children?.()}
    </form>

<script lang="ts">
import type {HTMLFormAttributes} from 'svelte/elements'

interface IProps extends HTMLFormAttributes {onsubmit: (e: any)=>any; state?: any}

let {children,...props} : IProps = $props()
const _onSubmit = async (e: any)=>{
    e.preventDefault()
    const btns = [...e.target.querySelectorAll('button[type=submit]')]
    btns.forEach((btn: any)=>{
        btn.disabled = true})
        await props.onsubmit?.(e)
    btns.forEach((btn: any)=>btn.disabled = false)
}
</script>
