// apps/tu-trader-sv/src/components/MenuItem.svelte
<script lang="ts">
    import type { HTMLAttributes } from "svelte/elements";

    interface IProps extends HTMLAttributes<any> {
        to?: string;
        title?: string;
        innerClass?: string;
        icon?: string;
    }
    const {
        to,
        innerClass,
        children,
        title,
        icon,
        class: _class,
        ...props
    }: IProps = $props();
</script>

<li class={"tooltip tooltip-right " + _class} data-tip={title} {...props}>
    {#if to}
        <nuxt-link {to} class={`${innerClass}`}>
            {#if icon}
                <i class={icon}></i>
            {/if}
            {@render children?.()}
        </nuxt-link>
    {:else}
        <span class={`${innerClass}`}>
            {#if icon}
                <i class={icon}></i>
            {/if}
            {@render children?.()}
        </span>
    {/if}
</li>

// apps/tu-trader/components/MenuItem.vue
<template>
    <li class="tooltip tooltip-right" :data-tip="title">
        <nuxt-link v-if="to" :to="to" :class="`${innerClass}`"><i v-if="icon" :class="icon"/> <slot/></nuxt-link>
        <span v-else :class="`${innerClass}`"><i v-if="icon" :class="icon"/> <span><slot/></span></span>
    </li>
     
</template>

<script setup lang="ts">

defineProps({
    to: {type: String},
    title: {type: String, default: ''},
    innerClass: {type: String},
    icon: {type: String},
})
</script>
