// apps/tu-trader-next/components/UAccordion.tsx
import React, { DetailsHTMLAttributes } from "react";

interface Props extends DetailsHTMLAttributes<{}> {
    children: React.ReactNode; label: React.ReactNode
}
const UAccordion: React.FC<Props> = ({ children, label }) => {
    return (
        <details className="collapse collapse-arrow border border-card bg-base-100 collapse-sm">
            <summary className="collapse-title text-l font-medium">
                {label}
            </summary>
            <div className="collapse-content">{children}</div>
        </details>
    );
};

export default UAccordion;

// apps/tu-trader/components/UAccordion.vue
<template>
    <details class="collapse collapse-arrow border border-card bg-base-100 collapse-sm">
        <summary class="collapse-title text-l font-medium">
            <slot name="label"/>
        </summary>
        <div class="collapse-content">
            <slot name="content"/>
        </div>
    </details>
</template>

<style lang="scss">
.collapse-content{
    //padding: 0 !important;
}
</style>
