// apps/tu-trader-sv/src/components/UInput.svelte

<input autocomplete="on" bind:value={value} class="{defClass}" {...props}/>

<script lang="ts">
    import type { HTMLInputAttributes } from "svelte/elements";


interface IProps extends HTMLInputAttributes{value?: any; override?: string;}

let {override = "", value = $bindable(),...props}: IProps = $props()
const defClass = override.split(" ").find((el) => el == "class")
    ? ""
    : "input input-bordered input-sm";


</script>

// apps/tu-trader/components/UInput.vue
<template>
    <input autocomplete="all" v-model="value" :class="defClass" />
</template>
<script setup lang="ts">
const props = withDefaults(
    defineProps<{ modelValue?: any; override: string }>(),
    { override: "" }
);
const defClass = props.override.split(" ").find((el) => el == "class")
    ? ""
    : "input input-bordered input-sm";

const emit = defineEmits(["update:model-value"]);
const value = computed({
    get: () => props.modelValue,
    set: (val) => {
        emit("update:model-value", val);
    },
});
</script>
