// apps/tu-trader-next/layouts/Default.tsx
"use client"
import { useDispatch, useSelector } from "react-redux";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import { useEffect, useState } from "react";
import { setUser } from "../redux/reducers/user";
import { setParents, setPlatforms, setReady, setStrategies } from "../redux/reducers/app";
import { RootState } from "../redux/store";
import Loader from "../components/Loader";
import {  pagesWithLayout, setSocket, socket } from "@/utils/constants";
import { sleep } from "@cmn/utils/functions";
import { io } from "socket.io-client";
import { localApi } from "@/utils/api";
import { BEND_URL } from "@/utils/constants";

const DefaultLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const dispatch = useDispatch();
    const appStore = useSelector((state: RootState) => state.app);
    const [isMounted, setIsMounted] = useState(false)
    useEffect(() => {
        setIsMounted(true)
        initSocket()
        init();
    }, []);

    const getUser = async () => {
        try {
            console.log("GETTING USER");
            const res = await localApi(true).post("/auth/login", {});
            dispatch(setUser(res.data.user));
        } catch (e) {
            console.log(e);
        }
    };

    const getStrategies = async () => {
        try {
            console.log("GETTING STRATEGIES...");
            const res = await localApi().get("/strategies");
            dispatch(setStrategies(res.data));
            console.log("GOT THE STRATEGIES");
        } catch (error) {
            console.log(error);
        }
    };
    const getPlatforms = async () => {
        try {
            console.log("GETTING PLATFORMS...");
            const res = await localApi().get("/platforms");
            dispatch(setPlatforms(res.data));
            console.log("GOT THE PLATFORMS");
        } catch (error) {
            console.log(error);
        }
    };
    const getParents = async () => {
        try {
            console.log("GETTING PARENTS...");
            const res = await localApi().get("/parents");
            dispatch(setParents(res.data));
            console.log("GOT THE PARENTS");
        } catch (error) {
            console.log(error);
        }
    };

    const initSocket = ()=>{
        try {
            console.log("DEFAULT MOUNTED")
            setSocket(
                io(
                    BEND_URL /* */ , {auth: {username: 'tonnidiaz',}, timeout: 100 * 100000000000}
                )
            );
            socket?.on("connect", () => {
                console.log(`IO CONNECTED`);
            });
            socket?.on("error", () => {
                console.log(`IO ERR`);
            });
           
        } catch (err) {
            console.log("IO INIT ERR");
            console.log(err);
        }
    }
    const init = async () => {
        console.log("Init");
        console.log(pagesWithLayout.indexOf(location.pathname ) == -1 );

        // await getUser();
        // getStrategies();
        // getParents()
        // getPlatforms()
        dispatch(setReady(true));
    };

    if (!isMounted) return
    return !appStore.ready ? (
      <Loader/>
    ) : (
        <>
            { pagesWithLayout.indexOf(location.pathname ) == -1 && <Navbar></Navbar>}
            <div className={pagesWithLayout.indexOf(location.pathname ) == -1 ? "tu-app" : ""}>
            { pagesWithLayout.indexOf(location.pathname ) == -1 && <Sidebar></Sidebar>}
                <main>{children}</main>
            </div>
            <div id="ctx-overlay"></div>
        </>
    );
};

export default DefaultLayout;

// apps/tu-trader/layouts/default.vue
<template>
    <Loader v-if="!ready" />
    <div v-else>
        <Navbar />
        <div class="tu-app">
            <Sidebar />
            <main style="padding: 0 10px"><slot /></main>
        </div>
    </div>
</template>
<script setup lang="ts">
import Navbar from "~/components/Navbar.vue";
import Sidebar from "~/components/Sidebar.vue";
import { useAppStore } from "~/src/stores/app";
import { useUserStore } from "~/src/stores/user";
import { setSocket } from "~/utils/constants";
import { Socket, io } from "socket.io-client";

const appStore = useAppStore();
const { setReady, setStrategies, setPlatforms, setParents } = appStore;
const { setUser } = useUserStore();
const { ready } = storeToRefs(useAppStore());

onMounted(() => {
    try {
        console.log("DEFAULT MOUNTED")
        setSocket(
            io(
                BEND_URL /* */ , {auth: {username: 'tonnidiaz',}, timeout: 100 * 100000000000}
            )
        );
        socket?.on("connect", () => {
            console.log(`IO CONNECTED`);
        });
        socket?.on("error", () => {
            console.log(`IO ERR`);
        });
       
    } catch (err) {
        console.log("IO INIT ERR");
        console.log(err);
    }
 socket?.on("strategies", ({ data, err }) => {
        if (err) {
            console.log(err);
            return;
        }
        setStrategies(data);
        console.log("GOT THE STRATEGIES");
    });
    socket?.on("platforms", ({ data, err }) => {
        if (err) {
            console.log(err);
            return;
        }
        setPlatforms(data);
        console.log("GOT THE PLATFORMS");
    });
    socket?.on("parents", ({ data, err }) => {
        if (err) {
            console.log(err);
            return;
        }
        setParents(data);
        console.log("GOT THE PARENTS");
    });
    init();
    
});

const getUser = async () => {
    try {
        console.log("GETTING USER");
        const res = await localApi(true).post("/auth/login", {});
        setUser(res.data.user);
    } catch (e) {
        console.log(e);
    }
};

const getStrategies = async () => {
    try {
        console.log("GETTING STRATEGIES...");
        socket?.emit('strategies')
        //const res = await api().get("/strategies");
        //setStrategies(res.data);
    } catch (error) {
        console.log(error);
    }
};
const getPlats = async () => {
    try {
        console.log("GETTING Platforms...");
        //socket?.emit('strategies')
        const res = await api().get("/platforms");
        setPlatforms(res.data);
    } catch (error) {
        console.log(error);
    }
};

const init = async () => {
    //console.log(pagesWithLayout.indexOf(location.pathname ) == -1 );
    await getUser();
    //console.log('GETTING PLATFORMS...');
    socket?.emit('platforms')
    socket?.emit('parents')
    await getStrategies();
    //await getPlats();
    setReady(true);
};
</script>
