// apps/tu-trader/components/TuDatePicker.vue
<template>
    <ctx-menu v-model="modalOpen">
        <template #toggler>
            <div class="btn btn-primary btn-sm"
           
            icon="i-heroicons-calendar-days-20-solid"
        >
            {{ format(new Date(date.start), "d MMM, yyy, hh:mm") }} -
            {{ format(new Date(date.end), "d MMM, yyy, hh:mm") }}
        </div>
        </template>
        <template #children>
                <div class="card p-2">
                <div class="card-header p-2">
                    <h3>Select range</h3>
                </div>
                <div
                    class="rounded-m sm:flex-row flex flex-col items-center justify-center gap-3"
                >
                    <UInput type="datetime-local" v-model="date.start" />
                    <UInput type="datetime-local" v-model="date.end" />
                </div> 
            </div>
             
        </template>
        
           
        
    </ctx-menu>
</template>
<script setup lang="ts">
import { format, isDate } from "date-fns";
const modalOpen = ref(false);

import { isValidDate } from "~/utils/funcs";

const props = defineProps({
    modelValue: {
        type: Object,
        default: {
            start: new Date(Date.now() - 2 * 24 * 3600 * 1000)
                .toISOString()
                .slice(0, 16),
            end: new Date().toISOString().slice(0, 16),
        },
    },
});

const emit = defineEmits(["update:model-value", "close"]);
const date = computed({
    get: () => props.modelValue,
    set: (val) => {
        emit("update:model-value", val)},
});


watch(()=>date, (val)=>{
    const _date = val.value
    const {start, end} = _date
    const y1 = start.split('-')[0]
    const y2 = end.split('-')[0]
    const _end = end?.replaceAll(y2, y1)
    if (isValidDate(_end)) val.value.end = _end
}, {immediate: true, deep: true})

</script>

// apps/tu-trader-next/components/TuDatePicker.tsx
import React, { useEffect, useState } from "react";
import CtxMenu from "./CtxMenu";
import { format, isDate } from "date-fns";
import UInput from "./UInput";
import { isValidDate } from "@/utils/funcs";

interface IDate {start: string; end: string}
interface IProps extends React.HTMLAttributes<{}> {
    value?: IDate;
    setValue?: (v: IDate) => any;
}

const defaultDate = {
    start: new Date(Date.now() - 2 * 24 * 3600 * 1000)
        .toISOString()
        .slice(0, 16),
    end: new Date().toISOString().slice(0, 16),
};

const TuDatePicker: React.FC<IProps> = ({ value = defaultDate, setValue }) => {
    const [modalOpen, setModalOpen] = useState(false);

    useEffect(() => {
        const { start, end } = value;
        const y1 = start.split("-")[0];
        const y2 = end.split("-")[0];
        const _end = end?.replaceAll(y2!, y1!);
        const _date = { ...value, end: _end }
        if (isValidDate(_end) && (_date.start != value.start || _date.end != value.end)) {
            setValue?.call(null, _date);}
    }, [value]);

;

    return (
        <CtxMenu
            open={modalOpen}
            setOpen={(v) => setModalOpen(v)}
            toggler={
                <div
                    className="btn btn-primary btn-sm"

                    // icon="i-heroicons-calendar-days-20-solid"
                >
                    {format(new Date(value.start), "d MMM, yyy, hh:mm")} -
                    {format(new Date(value.end), "d MMM, yyy, hh:mm")}
                </div>
            }
        >
            <div className="card p-2">
                <div className="card-header p-2">
                    <h3>Select range</h3>
                </div>
                <div className="rounded-m sm:flex-row flex flex-col items-center justify-center gap-3">
                    <UInput
                        type="datetime-local"
                        value={value.start}
                        onChange={(v) => setValue?.call(null,{ ...value, start: v })}
                    />
                    <UInput
                        type="datetime-local"
                        value={value.end}
                        onChange={(v) => setValue?.call(null,{ ...value, end: v })}
                    />
                </div>
            </div>
        </CtxMenu>
    );
};

export default TuDatePicker;
